# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: 'CI/CD'
description: 'CI/CD pipeline for React template with TypeScript, ESLint, Prettier, Jest, Lefthook, Playwright, and TailwindCSS'
author: 'Jagoda11'
inputs:
  node-version:
    description: 'ode.js version to use'
    required: true
    default: '26'
  install-dependencies:
    description: 'Whether to install dependencies'
    required: false
    default: 'true'
  run-tests:
    description: 'Whether to run tests'
    required: false
    default: 'true'
outputs:
  success-message:
    description: 'Message displayed upon successful execution'
runs:
  using: 'node24'
  main: 'dist/src/index.js'
branding:
  icon: 'skip-forward'
  color: 'blue'
