import type { GradeContent, GradeTab, GradeUnit } from '../types'

const TABS: readonly GradeTab[] = [
  { id: 1, titleKm: 'ថ្នាក់ទី ១', titleEn: 'Grade 1' },
  { id: 2, titleKm: 'ថ្នាក់ទី ២', titleEn: 'Grade 2' },
  { id: 3, titleKm: 'ថ្នាក់ទី ៣', titleEn: 'Grade 3' },
  { id: 4, titleKm: 'ថ្នាក់ទី ៤', titleEn: 'Grade 4' },
  { id: 5, titleKm: 'ថ្នាក់ទី ៥', titleEn: 'Grade 5' },
  { id: 6, titleKm: 'ថ្នាក់ទី ៦', titleEn: 'Grade 6' },
]

const UNITS: readonly GradeUnit[] = [
  {
    id: 1,
    unitLabel: 'Unit 1 • មេរៀនទី ១',
    titleKm: 'ចំនួន និងការរាប់',
    titleEn: 'Numbers & Counting up to 100',
    icon: 'pin',
    tone: 'primary',
    percent: 100,
    progressTone: 'primary',
    statusLabel: '100% រួចរាល់',
    lessonsLabel: '៥ មេរៀន • 5 Lessons (Complete)',
    current: false,
    completed: true,
    compact: false,
  },
  {
    id: 2,
    unitLabel: 'Unit 2 • មេរៀនទី ២',
    titleKm: 'វិធីបូកមានត្រាទុក',
    titleEn: 'Addition Focus & Carrying',
    description:
      'Learn two-digit column calculation, regrouping ones into tens, and mental addition tricks!',
    icon: 'add_circle',
    tone: 'primary',
    percent: 80,
    progressTone: 'secondary',
    statusLabel: 'កំពុងរៀន Current',
    lessonsLabel: 'មេរៀនទី ៤: រក្សាតួត្រាទុក',
    current: true,
    completed: false,
    compact: false,
  },
  {
    id: 3,
    unitLabel: 'Unit 3 • មេរៀនទី ៣',
    titleKm: 'វិធីដកខ្ចី',
    titleEn: 'Subtraction & Borrowing',
    icon: 'remove_circle',
    tone: 'secondary',
    percent: 60,
    progressTone: 'tertiary',
    statusLabel: 'វឌ្ឍនភាព 60%',
    lessonsLabel: 'Borrowing across tens and word challenges',
    current: false,
    completed: false,
    compact: false,
  },
  {
    id: 4,
    unitLabel: 'Unit 4 • មេរៀនទី ៤',
    titleKm: 'វិធីគុណមូលដ្ឋាន',
    titleEn: 'Multiplication Arrays (2, 5, 10)',
    icon: 'close',
    tone: 'tertiary',
    percent: 40,
    progressTone: 'primary',
    statusLabel: 'វឌ្ឍនភាព 40%',
    lessonsLabel: 'Grid groups, repeated additions',
    current: false,
    completed: false,
    compact: false,
  },
  {
    id: 5,
    unitLabel: 'Unit 5 • មេរៀន ៥',
    titleKm: 'ធរណីមាត្រ',
    titleEn: 'Shapes & Geometry',
    icon: 'shapes',
    tone: 'primary',
    percent: 20,
    progressTone: 'outline',
    statusLabel: '20%',
    lessonsLabel: '1/5',
    current: false,
    completed: false,
    compact: true,
  },
  {
    id: 6,
    unitLabel: 'Unit 6 • មេរៀន ៦',
    titleKm: 'រង្វាស់រង្វាល់ & ពេលវេលា',
    titleEn: 'Time & Money (Riel)',
    icon: 'schedule',
    tone: 'secondary',
    percent: 10,
    progressTone: 'outline',
    statusLabel: '10%',
    lessonsLabel: '1/5',
    current: false,
    completed: false,
    compact: true,
  },
]

export const GRADE_CONTENT: GradeContent = {
  breadcrumb: ['Mathematics World', 'MOEYS Elementary Standard'],
  titleKm: 'ជ្រើសរើសថ្នាក់រៀន',
  titleEn: '(Select Grade)',
  tabs: TABS,
  hero: {
    unit: 'Grade 2 • Unit 2',
    titleKm: 'ការបូកមានត្រាទុក',
    titleEn: 'Addition with Carrying (Regrouping 2-digit numbers)',
    subtitle: 'Lesson 4 of 5',
    icon: 'add_circle',
    progress: { percent: 80, done: 4, total: 5 },
  },
  equation: {
    addends: [27, 15],
    result: 42,
    note: 'Regroup 12 ones ➔ 1 ten & 2 ones',
  },
  units: UNITS,
  dailyQuest: {
    title: 'Daily Math Quest',
    reward: '+50 XP',
    description: 'Complete 1 carrying exercise today!',
    streak: 'Streak maintained: 7 days 🔥',
    tutorName: 'លោកគ្រូ AI KELA',
    tutorMessage:
      '"Dara, you are just 1 lesson away from your Addition Master Badge!"',
  },
}
