import { DRAGON_URL } from './assets'
import type { HomeContent } from '../types'

export const HOME_CONTENT: HomeContent = {
  greetingKm: 'សួស្ដី Dara! 👋',
  greetingEn: 'Ready to discover math magic today?',
  level: 'Level 4',
  levelTitle: 'Lv. 4 Math Explorer',
  xp: { percent: 68, done: 340, total: 500 },
  quickStats: [
    {
      id: 'streak',
      icon: '🔥',
      value: '7d',
      label: 'Streak',
      tone: 'secondary',
    },
    {
      id: 'badges',
      icon: '⭐',
      value: '12',
      label: 'Badges',
      tone: 'tertiary',
    },
    {
      id: 'coins',
      icon: '🪙',
      value: '1,250',
      label: 'Coins',
      tone: 'tertiary',
    },
  ],
  activeLesson: {
    unit: 'Unit 2',
    titleKm: 'វិធីបូក',
    titleEn: 'Addition Focus',
    subtitle: 'ការបូកមានត្រាទុក (Addition with Carrying) • Grade 2',
    icon: 'add',
    progress: { percent: 80, done: 4, total: 5 },
  },
  companion: {
    name: 'Sparky the Dragon',
    level: 'Lv.4',
    status: 'Status: Happy & energised',
    boost: 'Companion Boost: +10% Coins!',
    imageUrl: DRAGON_URL,
    imageAlt: 'Cute 3D baby dragon maths companion named Sparky',
  },
  quests: [
    {
      id: 'daily-blast',
      title: 'Daily Math Blast ⚡',
      subtitle: '60s Rapid Speed Challenge',
      icon: 'bolt',
      tone: 'tertiary',
      reward: '+50 🪙',
      action: 'Start Now',
      completed: false,
    },
    {
      id: 'unit-1',
      title: 'ចំនួន និងការរាប់ (Numbers)',
      subtitle: 'បានរៀបចប់សព្វគ្រប់ (Completed)',
      unit: 'Unit 1 • ជំពូកទី ១',
      icon: 'counter_1',
      tone: 'primary',
      action: 'Review',
      progress: { percent: 100, done: 6, total: 6 },
      completed: true,
    },
    {
      id: 'unit-3',
      title: 'វិធីដក • Subtraction Quest',
      subtitle: 'វិធីដកមានខ្ចី (Regrouping practice)',
      unit: 'Unit 3 • ជំពូកទី ៣',
      icon: 'remove',
      tone: 'secondary',
      action: 'Continue',
      progress: { percent: 60, done: 3, total: 5 },
      completed: false,
    },
  ],
  coachTitle: 'Need help solving a problem?',
  coachSubtitle: 'Ask your AI Math Coach in ភាសាខ្មែរ or English',
}
